#on: 
#  release:
#    types:
#      - created

name: trojan-go

on:
# 编辑触发    
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: trojan-go Package  
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://archive.openwrt.org/releases/19.07.3/targets/kirkwood/generic/openwrt-sdk-19.07.3-kirkwood_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz
    steps:
    
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@v1
      
    - name: Install env dependencies
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool libev-dev libc-ares-dev libudns-dev libncurses-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean 
    
    - name: TAG
      run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
          
    - name: Download SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        wget -q "${SDK_URL}"
        tar xJf openwrt-sdk-*.tar.xz -C ../
        mv -f "${GITHUB_WORKSPACE}" ../src
        mv ../openwrt-sdk-* "${GITHUB_WORKSPACE}"
        
    - name: Prepare targets
      env:
        REPF: ${{ github.repository }}
        PKGN: ${{ 'trojan-go' }}
      run: |
        REP=$(basename "${REPF}")
        mv -vf ../src "package/${PKGN}"
        
    - name: Load custom configuration
      env:
        DEBIAN_FRONTEND: noninteractive
        CONFIG_FILE: '.config'
        REPF: ${{ github.repository }}
        PKGN: ${{ 'trojan-go' }}
      run: |
        REP=$(basename "${REPF}")
        ./scripts/feeds update -a
        ./scripts/feeds install golang c-ares libev libopenssl libsodium mbedtls pcre libncursesw6
        [ -e "package/${PKGN}/${CONFIG_FILE}" ] && mv "${CONFIG}" .config
        make defconfig
           
    - name: Compile Package
      env:
        DEBIAN_FRONTEND: noninteractive
        PKGN: ${{ 'trojan-go' }}
      run: |
        make package/${PKGN}/compile -j$(nproc) V=s
        mkdir ../bin
        find bin/ -type f -name "*${PKGN}*" | xargs -t -i mv -vf {} ../bin
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ../bin/*.ipk
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
